# Generated by Django 4.1.7 on 2023-04-05 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samasya', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aprad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('village', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='samasya',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apradreason', to='samasya.aprad'),
        ),
        migrations.AlterField(
            model_name='samasya',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apradtype', to='samasya.aprad'),
        ),
    ]
