# Generated by Django 4.1.7 on 2023-04-05 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samasya', '0002_aprad_alter_samasya_address_alter_samasya_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samasya',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Apradreason', to='samasya.aprad'),
        ),
        migrations.AlterField(
            model_name='samasya',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Apradtype', to='samasya.aprad'),
        ),
    ]
