# Generated by Django 4.1.7 on 2023-04-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samasya', '0003_alter_samasya_address_alter_samasya_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprad',
            name='code',
            field=models.IntegerField(max_length=10),
        ),
    ]
