# Generated by Django 4.1.7 on 2023-04-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samasya', '0005_alter_aprad_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprad',
            name='code',
            field=models.IntegerField(),
        ),
    ]
